### ISSUE TITLE
Use workbench with another server

### ISSUE THREAD

**Issue by olivierguerriat** [lihaoyi/workbench#18]
I use a Spray server to serve the HTML and static files but I would like to use the workbench plugin (refresh on packageJS & console forwarding) in the same way I use [LiveReload](http://livereload.com) for CSS changes.

I tried to include `<script type="text/javascript" src="http://localhost:12345/workbench.js"></script>` in the HTML, but it doesn't work well in Chrome and not at all in Safari. The `Access-Control-Allow-Origin` header seems to cause troubles.

Is that a supported use case? How should I do it?

**Comment by lihaoyi** [comment]
I haven't tried, but it could probably be made to work. If you're willing to put in some elbow grease, you could try cloning the repo and fiddling with workbench's own server (also Spray!) to make the CORS things like up properly.
