### ISSUE TITLE
Fix missing client-opt.js.map

### ISSUE THREAD

**Issue by hamero** [lihaoyi/workbench#19]
Project that uses workbench.js gets an annoying 404 on client-opt.js.map in javascript console.

A quick fix would be to publish a new workbench version with emitSourceMaps := false

A proper fix would be to include client-opt.js.map (pointing to tagged github source) with the jar and have the Server serving it.

**Comment by Daxten** [comment]
+1

**Comment by ochrons** [comment]
This seems to be fixed.
