### ISSUE TITLE
Allow client to specify custom url -> file mapping

### ISSUE THREAD

**Issue by naksu** [lihaoyi/workbench#26]
I'd like to keep production and development URLs the same, and thus to avoid using urls to `target` directory. It would be good to allow client to provide mapping between the URLs and files. 

I made a prototype in 76a101714081af4bc5da4c18536e53bc60a71820.

What do you think? I'm happy to make a pull request if the commit is ok.

**Comment by torstenrudolf** [comment]
I really would like to have this feature too.
@jodersky  @lihaoyi  what do you think about this improvement?

**Comment by jodersky** [comment]
Having a single URL or, alternatively, enabling users to explore files under target/ through the browser would be a great enhancement in usability!
Regarding the initial request "I'd like to keep production and development URLs the same" I'm not sure I fully understand what a production URL is in that context. Workbench is a ScalaJS development tool, how would it be used in production?

**Comment by ochrons** [comment]
Fixed via #37
