### ISSUE TITLE
500 errors from /notifications with >1 client

### ISSUE THREAD

**Issue by nornagon** [lihaoyi/workbench#32]
When more than one client connects to workbench, the js console spouts a 500 error every 40 seconds or so, and fails to refresh on rebuild. This was super confusing and hard to debug. It'd be awesome to support more than one client pointing at the server, but failing that it'd be nice to have a friendlier error message :)

**Comment by torstenrudolf** [comment]
thanks for the diagnostic...I spent quite some time trying to figure out why it wouldn't reload anymore

**Comment by ochrons** [comment]
Fixed in 0.3.1
