### ISSUE TITLE
Add support for SBT 1.0

### ISSUE THREAD

**Issue by inigo** [lihaoyi/workbench#40]
SBT has upgraded to version 1.0, which has involved some breaking changes.

Release notes are at:

http://www.scala-sbt.org/1.0/docs/sbt-1.0-Release-Notes.html

**Comment by shaagerup** [comment]
I did the upgrade to SBT 1.0.2 here: https://github.com/lihaoyi/workbench/pull/41 -- You can test it, and report back bugs :smiley:

**Comment by inigo** [comment]
Works for me - thank you! (I can't merge it, though)

**Comment by nafg** [comment]
@lihaoyi want to merge?

**Comment by lihaoyi** [comment]
@nafg do you still use this? I haven't touched this in a while, so ideally I'd find someone else who still does, give them merge/publish access, and let them merge it

**Comment by nafg** [comment]
Kind of... I have a project that uses some of its feature. But I don't know
it well enough to take responsibility for the pull request.
Any reason not to merge it? If something goes wrong people can report it,
stick to the previous version meanwhile, and you can publish a fix later.

**Comment by ochrons** [comment]
I'm also using this for local testing of things in many libs, so SBT 1.0 support would be nice to have!

**Comment by lihaoyi** [comment]
@ochrons want commit/publish access? Then you can merge/publish this one and any other PRs/changes you would like

**Comment by ochrons** [comment]
Sure, I can take over yet another of your projects 😜

**Comment by lihaoyi** [comment]
@ochrons great, I gave you collaborator access and sent you the sonatype token. Feel free to do whatever!

**Comment by ochrons** [comment]
This is now implemented in master, will go out in 0.4.0
